<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://j2ee.netbeans.org/wsdl/NDR-StoreDocument-v0-0/StoreDocument" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="NDR-StoreDocument-v0-0_CA" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:msg="http://www.wales.nhs.uk/namespaces/MessageRelease2" targetNamespace="NDR-StoreDocument-v0-0_CA">
	<types>
		<xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/NDR-StoreDocument-v0-0/StoreDocument">
			<xsd:import namespace="http://www.wales.nhs.uk/namespaces/MessageRelease2" schemaLocation="XSD/Messages/ErrorResponse-v1-0.xsd"/>
			<xsd:import namespace="http://www.wales.nhs.uk/namespaces/MessageRelease2" schemaLocation="XSD/Messages/StoreDocumentRequest-v1-0.xsd"/>
			<xsd:import namespace="http://www.wales.nhs.uk/namespaces/MessageRelease2" schemaLocation="XSD/Messages/StoreDocumentResponse-v1-0.xsd"/>
		</xsd:schema>
	</types>
	<message name="StoreDocumentRequest">
		<part name="part1" element="msg:StoreDocumentRequest"/>
	</message>
	<message name="StoreDocumentResponse">
		<part name="part1" element="msg:StoreDocumentResponse"/>
	</message>
	<message name="StoreDocumentFault">
		<part name="part1" element="msg:ErrorResponse"/>
	</message>
	<portType name="StoreDocumentPortType">
		<operation name="StoreDocument">
			<input name="input1" message="tns:StoreDocumentRequest"/>
			<output name="output1" message="tns:StoreDocumentResponse"/>
			<fault name="fault1" message="tns:StoreDocumentFault"/>
		</operation>
	</portType>
	<binding name="casaBinding1" type="tns:StoreDocumentPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="StoreDocument">
			<soap:operation soapAction="StoreDocument"/>
			<input name="input1">
				<soap:body use="literal"/>
			</input>
			<output name="output1">
				<soap:body use="literal"/>
			</output>
			<fault name="fault1">
				<soap:fault name="fault1" use="literal"/>
			</fault>
		</operation>
	</binding>
	<service name="NDR-StoreDocument-v0-0_CAService1">
		<port name="casaPort1" binding="tns:casaBinding1">
			<soap:address location="http://ihd03srviwt0001.cymru.nhs.uk:9080/NDR-StoreDocument/casaPort1"/>
		</port>
	</service>
</definitions>
