// Code generated by protoc-gen-go. DO NOT EDIT.
// source: empi.proto

package apiv1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Patient_Gender int32

const (
	Patient_UNKNOWN Patient_Gender = 0
	Patient_MALE    Patient_Gender = 1
	Patient_FEMALE  Patient_Gender = 2
)

var Patient_Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "MALE",
	2: "FEMALE",
}
var Patient_Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"MALE":    1,
	"FEMALE":  2,
}

func (x Patient_Gender) String() string {
	return proto.EnumName(Patient_Gender_name, int32(x))
}
func (Patient_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_empi_b6e617490668ce7b, []int{0, 0}
}

type CymruEmpiRequest_Authority int32

const (
	CymruEmpiRequest_UNKNOWN          CymruEmpiRequest_Authority = 0
	CymruEmpiRequest_NHS_NUMBER       CymruEmpiRequest_Authority = 1
	CymruEmpiRequest_SWANSEA          CymruEmpiRequest_Authority = 3
	CymruEmpiRequest_ANEURIN_BEVAN    CymruEmpiRequest_Authority = 4
	CymruEmpiRequest_BCU_CENTRAL      CymruEmpiRequest_Authority = 5
	CymruEmpiRequest_BCU_MAELOR       CymruEmpiRequest_Authority = 6
	CymruEmpiRequest_BCU_WEST         CymruEmpiRequest_Authority = 7
	CymruEmpiRequest_CWM_TAF          CymruEmpiRequest_Authority = 8
	CymruEmpiRequest_CARDIFF_AND_VALE CymruEmpiRequest_Authority = 9
	CymruEmpiRequest_HYWEL_DDA        CymruEmpiRequest_Authority = 10
	CymruEmpiRequest_POWYS            CymruEmpiRequest_Authority = 11
)

var CymruEmpiRequest_Authority_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "NHS_NUMBER",
	3:  "SWANSEA",
	4:  "ANEURIN_BEVAN",
	5:  "BCU_CENTRAL",
	6:  "BCU_MAELOR",
	7:  "BCU_WEST",
	8:  "CWM_TAF",
	9:  "CARDIFF_AND_VALE",
	10: "HYWEL_DDA",
	11: "POWYS",
}
var CymruEmpiRequest_Authority_value = map[string]int32{
	"UNKNOWN":          0,
	"NHS_NUMBER":       1,
	"SWANSEA":          3,
	"ANEURIN_BEVAN":    4,
	"BCU_CENTRAL":      5,
	"BCU_MAELOR":       6,
	"BCU_WEST":         7,
	"CWM_TAF":          8,
	"CARDIFF_AND_VALE": 9,
	"HYWEL_DDA":        10,
	"POWYS":            11,
}

func (x CymruEmpiRequest_Authority) String() string {
	return proto.EnumName(CymruEmpiRequest_Authority_name, int32(x))
}
func (CymruEmpiRequest_Authority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_empi_b6e617490668ce7b, []int{6, 0}
}

type Patient struct {
	Lastname   string               `protobuf:"bytes,1,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Firstnames string               `protobuf:"bytes,2,opt,name=firstnames,proto3" json:"firstnames,omitempty"`
	Title      string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Gender     Patient_Gender       `protobuf:"varint,4,opt,name=gender,proto3,enum=apiv1.Patient_Gender" json:"gender,omitempty"`
	BirthDate  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	// Types that are valid to be assigned to Deceased:
	//	*Patient_DeceasedDate
	//	*Patient_DeceasedBoolean
	Deceased             isPatient_Deceased `protobuf_oneof:"deceased"`
	Surgery              string             `protobuf:"bytes,8,opt,name=surgery,proto3" json:"surgery,omitempty"`
	GeneralPractitioner  string             `protobuf:"bytes,9,opt,name=general_practitioner,json=generalPractitioner,proto3" json:"general_practitioner,omitempty"`
	Identifiers          []*Identifier      `protobuf:"bytes,10,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	Addresses            []*Address         `protobuf:"bytes,11,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Telephones           []*Telephone       `protobuf:"bytes,12,rep,name=telephones,proto3" json:"telephones,omitempty"`
	Emails               []string           `protobuf:"bytes,13,rep,name=emails,proto3" json:"emails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Patient) Reset()         { *m = Patient{} }
func (m *Patient) String() string { return proto.CompactTextString(m) }
func (*Patient) ProtoMessage()    {}
func (*Patient) Descriptor() ([]byte, []int) {
	return fileDescriptor_empi_b6e617490668ce7b, []int{0}
}
func (m *Patient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patient.Unmarshal(m, b)
}
func (m *Patient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patient.Marshal(b, m, deterministic)
}
func (dst *Patient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patient.Merge(dst, src)
}
func (m *Patient) XXX_Size() int {
	return xxx_messageInfo_Patient.Size(m)
}
func (m *Patient) XXX_DiscardUnknown() {
	xxx_messageInfo_Patient.DiscardUnknown(m)
}

var xxx_messageInfo_Patient proto.InternalMessageInfo

type isPatient_Deceased interface {
	isPatient_Deceased()
}

type Patient_DeceasedDate struct {
	DeceasedDate *timestamp.Timestamp `protobuf:"bytes,6,opt,name=deceased_date,json=deceasedDate,proto3,oneof"`
}
type Patient_DeceasedBoolean struct {
	DeceasedBoolean bool `protobuf:"varint,7,opt,name=deceased_boolean,json=deceasedBoolean,proto3,oneof"`
}

func (*Patient_DeceasedDate) isPatient_Deceased()    {}
func (*Patient_DeceasedBoolean) isPatient_Deceased() {}

func (m *Patient) GetDeceased() isPatient_Deceased {
	if m != nil {
		return m.Deceased
	}
	return nil
}

func (m *Patient) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Patient) GetFirstnames() string {
	if m != nil {
		return m.Firstnames
	}
	return ""
}

func (m *Patient) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Patient) GetGender() Patient_Gender {
	if m != nil {
		return m.Gender
	}
	return Patient_UNKNOWN
}

func (m *Patient) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *Patient) GetDeceasedDate() *timestamp.Timestamp {
	if x, ok := m.GetDeceased().(*Patient_DeceasedDate); ok {
		return x.DeceasedDate
	}
	return nil
}

func (m *Patient) GetDeceasedBoolean() bool {
	if x, ok := m.GetDeceased().(*Patient_DeceasedBoolean); ok {
		return x.DeceasedBoolean
	}
	return false
}

func (m *Patient) GetSurgery() string {
	if m != nil {
		return m.Surgery
	}
	return ""
}

func (m *Patient) GetGeneralPractitioner() string {
	if m != nil {
		return m.GeneralPractitioner
	}
	return ""
}

func (m *Patient) GetIdentifiers() []*Identifier {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *Patient) GetAddresses() []*Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Patient) GetTelephones() []*Telephone {
	if m != nil {
		return m.Telephones
	}
	return nil
}

func (m *Patient) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Patient) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Patient_OneofMarshaler, _Patient_OneofUnmarshaler, _Patient_OneofSizer, []interface{}{
		(*Patient_DeceasedDate)(nil),
		(*Patient_DeceasedBoolean)(nil),
	}
}

func _Patient_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Patient)
	// deceased
	switch x := m.Deceased.(type) {
	case *Patient_DeceasedDate:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeceasedDate); err != nil {
			return err
		}
	case *Patient_DeceasedBoolean:
		t := uint64(0)
		if x.DeceasedBoolean {
			t = 1
		}
		b.EncodeVarint(7<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("Patient.Deceased has unexpected type %T", x)
	}
	return nil
}

func _Patient_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Patient)
	switch tag {
	case 6: // deceased.deceased_date
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(timestamp.Timestamp)
		err := b.DecodeMessage(msg)
		m.Deceased = &Patient_DeceasedDate{msg}
		return true, err
	case 7: // deceased.deceased_boolean
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Deceased = &Patient_DeceasedBoolean{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _Patient_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Patient)
	// deceased
	switch x := m.Deceased.(type) {
	case *Patient_DeceasedDate:
		s := proto.Size(x.DeceasedDate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Patient_DeceasedBoolean:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Period struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Period) Reset()         { *m = Period{} }
func (m *Period) String() string { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()    {}
func (*Period) Descriptor() ([]byte, []int) {
	return fileDescriptor_empi_b6e617490668ce7b, []int{1}
}
func (m *Period) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Period.Unmarshal(m, b)
}
func (m *Period) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Period.Marshal(b, m, deterministic)
}
func (dst *Period) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Period.Merge(dst, src)
}
func (m *Period) XXX_Size() int {
	return xxx_messageInfo_Period.Size(m)
}
func (m *Period) XXX_DiscardUnknown() {
	xxx_messageInfo_Period.DiscardUnknown(m)
}

var xxx_messageInfo_Period proto.InternalMessageInfo

func (m *Period) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Period) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

type Identifier struct {
	System               string   `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_empi_b6e617490668ce7b, []int{2}
}
func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (dst *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(dst, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetSystem() string {
	if m != nil {
		return m.System
	}
	return ""
}

func (m *Identifier) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Address struct {
	Address1             string   `protobuf:"bytes,1,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2             string   `protobuf:"bytes,2,opt,name=address2,proto3" json:"address2,omitempty"`
	Address3             string   `protobuf:"bytes,3,opt,name=address3,proto3" json:"address3,omitempty"`
	Postcode             string   `protobuf:"bytes,4,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Period               *Period  `protobuf:"bytes,6,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_empi_b6e617490668ce7b, []int{3}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *Address) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *Address) GetAddress3() string {
	if m != nil {
		return m.Address3
	}
	return ""
}

func (m *Address) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetPeriod() *Period {
	if m != nil {
		return m.Period
	}
	return nil
}

type Telephone struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Telephone) Reset()         { *m = Telephone{} }
func (m *Telephone) String() string { return proto.CompactTextString(m) }
func (*Telephone) ProtoMessage()    {}
func (*Telephone) Descriptor() ([]byte, []int) {
	return fileDescriptor_empi_b6e617490668ce7b, []int{4}
}
func (m *Telephone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telephone.Unmarshal(m, b)
}
func (m *Telephone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telephone.Marshal(b, m, deterministic)
}
func (dst *Telephone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telephone.Merge(dst, src)
}
func (m *Telephone) XXX_Size() int {
	return xxx_messageInfo_Telephone.Size(m)
}
func (m *Telephone) XXX_DiscardUnknown() {
	xxx_messageInfo_Telephone.DiscardUnknown(m)
}

var xxx_messageInfo_Telephone proto.InternalMessageInfo

func (m *Telephone) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Telephone) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RawCymruEmpiRequest struct {
	Authority            string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Identifier           string   `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawCymruEmpiRequest) Reset()         { *m = RawCymruEmpiRequest{} }
func (m *RawCymruEmpiRequest) String() string { return proto.CompactTextString(m) }
func (*RawCymruEmpiRequest) ProtoMessage()    {}
func (*RawCymruEmpiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_empi_b6e617490668ce7b, []int{5}
}
func (m *RawCymruEmpiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawCymruEmpiRequest.Unmarshal(m, b)
}
func (m *RawCymruEmpiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawCymruEmpiRequest.Marshal(b, m, deterministic)
}
func (dst *RawCymruEmpiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawCymruEmpiRequest.Merge(dst, src)
}
func (m *RawCymruEmpiRequest) XXX_Size() int {
	return xxx_messageInfo_RawCymruEmpiRequest.Size(m)
}
func (m *RawCymruEmpiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawCymruEmpiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawCymruEmpiRequest proto.InternalMessageInfo

func (m *RawCymruEmpiRequest) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *RawCymruEmpiRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type CymruEmpiRequest struct {
	Authority            CymruEmpiRequest_Authority `protobuf:"varint,1,opt,name=authority,proto3,enum=apiv1.CymruEmpiRequest_Authority" json:"authority,omitempty"`
	Identifier           string                     `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CymruEmpiRequest) Reset()         { *m = CymruEmpiRequest{} }
func (m *CymruEmpiRequest) String() string { return proto.CompactTextString(m) }
func (*CymruEmpiRequest) ProtoMessage()    {}
func (*CymruEmpiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_empi_b6e617490668ce7b, []int{6}
}
func (m *CymruEmpiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CymruEmpiRequest.Unmarshal(m, b)
}
func (m *CymruEmpiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CymruEmpiRequest.Marshal(b, m, deterministic)
}
func (dst *CymruEmpiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CymruEmpiRequest.Merge(dst, src)
}
func (m *CymruEmpiRequest) XXX_Size() int {
	return xxx_messageInfo_CymruEmpiRequest.Size(m)
}
func (m *CymruEmpiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CymruEmpiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CymruEmpiRequest proto.InternalMessageInfo

func (m *CymruEmpiRequest) GetAuthority() CymruEmpiRequest_Authority {
	if m != nil {
		return m.Authority
	}
	return CymruEmpiRequest_UNKNOWN
}

func (m *CymruEmpiRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func init() {
	proto.RegisterType((*Patient)(nil), "apiv1.Patient")
	proto.RegisterType((*Period)(nil), "apiv1.Period")
	proto.RegisterType((*Identifier)(nil), "apiv1.Identifier")
	proto.RegisterType((*Address)(nil), "apiv1.Address")
	proto.RegisterType((*Telephone)(nil), "apiv1.Telephone")
	proto.RegisterType((*RawCymruEmpiRequest)(nil), "apiv1.RawCymruEmpiRequest")
	proto.RegisterType((*CymruEmpiRequest)(nil), "apiv1.CymruEmpiRequest")
	proto.RegisterEnum("apiv1.Patient_Gender", Patient_Gender_name, Patient_Gender_value)
	proto.RegisterEnum("apiv1.CymruEmpiRequest_Authority", CymruEmpiRequest_Authority_name, CymruEmpiRequest_Authority_value)
}

func init() { proto.RegisterFile("empi.proto", fileDescriptor_empi_b6e617490668ce7b) }

var fileDescriptor_empi_b6e617490668ce7b = []byte{
	// 807 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdf, 0x6f, 0xe3, 0x44,
	0x10, 0xae, 0xdb, 0xc6, 0x89, 0x27, 0x4d, 0xcf, 0xb7, 0x57, 0x90, 0x55, 0x21, 0x08, 0x91, 0x90,
	0x22, 0xf5, 0xf0, 0x5d, 0xd3, 0x27, 0x78, 0x41, 0x4e, 0xe2, 0xd2, 0x8a, 0xd6, 0x8d, 0x36, 0xe9,
	0x45, 0xc7, 0x8b, 0xe5, 0xc4, 0xd3, 0x74, 0x25, 0xff, 0x62, 0x77, 0x73, 0x90, 0x7f, 0x89, 0x67,
	0x9e, 0xf8, 0x8b, 0xf8, 0x33, 0x90, 0xd7, 0xeb, 0x24, 0x1c, 0xd2, 0x21, 0xde, 0xfc, 0xcd, 0xf7,
	0xcd, 0x78, 0x67, 0xf6, 0x9b, 0x05, 0xc0, 0xb4, 0x60, 0x6e, 0xc1, 0x73, 0x99, 0x93, 0x46, 0x54,
	0xb0, 0x0f, 0x97, 0xe7, 0x5f, 0xad, 0xf2, 0x7c, 0x95, 0xe0, 0x1b, 0x15, 0x5c, 0xac, 0x9f, 0xde,
	0x48, 0x96, 0xa2, 0x90, 0x51, 0x5a, 0x54, 0xba, 0xde, 0x5f, 0xc7, 0xd0, 0x9c, 0x44, 0x92, 0x61,
	0x26, 0xc9, 0x39, 0xb4, 0x92, 0x48, 0xc8, 0x2c, 0x4a, 0xd1, 0x31, 0xba, 0x46, 0xdf, 0xa2, 0x5b,
	0x4c, 0xbe, 0x04, 0x78, 0x62, 0xbc, 0x02, 0xc2, 0x39, 0x54, 0xec, 0x5e, 0x84, 0x9c, 0x41, 0x43,
	0x32, 0x99, 0xa0, 0x73, 0xa4, 0xa8, 0x0a, 0x90, 0x6f, 0xc1, 0x5c, 0x61, 0x16, 0x23, 0x77, 0x8e,
	0xbb, 0x46, 0xff, 0x74, 0xf0, 0x99, 0xab, 0x8e, 0xe5, 0xea, 0x3f, 0xba, 0x3f, 0x2a, 0x92, 0x6a,
	0x11, 0xf9, 0x0e, 0x60, 0xc1, 0xb8, 0x7c, 0x0e, 0xe3, 0x48, 0xa2, 0xd3, 0xe8, 0x1a, 0xfd, 0xf6,
	0xe0, 0xdc, 0xad, 0x5a, 0x70, 0xeb, 0x16, 0xdc, 0x59, 0xdd, 0x02, 0xb5, 0x94, 0x7a, 0x1c, 0x49,
	0x24, 0x1e, 0x74, 0x62, 0x5c, 0x62, 0x24, 0x30, 0xae, 0xb2, 0xcd, 0xff, 0xca, 0xbe, 0x39, 0xa0,
	0x27, 0x75, 0x8a, 0x2a, 0x71, 0x01, 0xf6, 0xb6, 0xc4, 0x22, 0xcf, 0x13, 0x8c, 0x32, 0xa7, 0xd9,
	0x35, 0xfa, 0xad, 0x9b, 0x03, 0xfa, 0xa2, 0x66, 0x86, 0x15, 0x41, 0x1c, 0x68, 0x8a, 0x35, 0x5f,
	0x21, 0xdf, 0x38, 0x2d, 0xd5, 0x71, 0x0d, 0xc9, 0x25, 0x9c, 0xad, 0x30, 0x43, 0x1e, 0x25, 0x61,
	0xc1, 0xa3, 0xa5, 0x64, 0x92, 0xe5, 0x19, 0x72, 0xc7, 0x52, 0xb2, 0x57, 0x9a, 0x9b, 0xec, 0x51,
	0xe4, 0x0a, 0xda, 0x2c, 0xc6, 0x4c, 0xb2, 0x27, 0x86, 0x5c, 0x38, 0xd0, 0x3d, 0xea, 0xb7, 0x07,
	0x2f, 0xf5, 0xac, 0x6e, 0xb7, 0x0c, 0xdd, 0x57, 0x91, 0xd7, 0x60, 0x45, 0x71, 0xcc, 0x51, 0x08,
	0x14, 0x4e, 0x5b, 0xa5, 0x9c, 0xea, 0x14, 0xaf, 0x8a, 0xd3, 0x9d, 0x80, 0xbc, 0x05, 0x90, 0x98,
	0x60, 0xf1, 0x9c, 0x67, 0x28, 0x9c, 0x13, 0x25, 0xb7, 0xb5, 0x7c, 0x56, 0x13, 0x74, 0x4f, 0x43,
	0x3e, 0x07, 0x13, 0xd3, 0x88, 0x25, 0xc2, 0xe9, 0x74, 0x8f, 0xfa, 0x16, 0xd5, 0xa8, 0x77, 0x01,
	0x66, 0x75, 0x6d, 0xa4, 0x0d, 0xcd, 0xc7, 0xe0, 0xa7, 0xe0, 0x61, 0x1e, 0xd8, 0x07, 0xa4, 0x05,
	0xc7, 0xf7, 0xde, 0x9d, 0x6f, 0x1b, 0x04, 0xc0, 0xbc, 0xf6, 0xd5, 0xf7, 0xe1, 0x10, 0xa0, 0x55,
	0x4f, 0xae, 0xf7, 0x0c, 0xe6, 0x04, 0x39, 0xcb, 0x63, 0xf2, 0x16, 0x1a, 0x42, 0x46, 0x5c, 0x2a,
	0x97, 0x7d, 0xfa, 0x8a, 0x2b, 0x21, 0x79, 0x0d, 0x47, 0x98, 0xc5, 0xca, 0x77, 0x9f, 0xd6, 0x97,
	0xb2, 0xde, 0xf7, 0x00, 0xbb, 0xa9, 0x95, 0x8d, 0x88, 0x8d, 0x90, 0x98, 0x6a, 0x53, 0x6b, 0x54,
	0x5a, 0xf6, 0x43, 0x94, 0xac, 0x51, 0xbb, 0xb9, 0x02, 0xbd, 0x3f, 0x0d, 0x68, 0xea, 0xf9, 0x95,
	0x0b, 0xa1, 0x27, 0x78, 0x59, 0x2f, 0x44, 0x8d, 0xf7, 0xb8, 0x81, 0x2e, 0xb0, 0xc5, 0x7b, 0xdc,
	0x95, 0xde, 0x87, 0x2d, 0x2e, 0xb9, 0x22, 0x17, 0x72, 0x99, 0xc7, 0xa8, 0x96, 0xc2, 0xa2, 0x5b,
	0x5c, 0x9a, 0x6a, 0x99, 0xaf, 0x33, 0xc9, 0x37, 0xca, 0xfc, 0x16, 0xad, 0x21, 0xf9, 0x06, 0xcc,
	0x42, 0xcd, 0x4e, 0xfb, 0xba, 0x53, 0x2f, 0x92, 0x0a, 0x52, 0x4d, 0xf6, 0x7c, 0xb0, 0xb6, 0x97,
	0x59, 0xf6, 0x9d, 0xad, 0xd3, 0x05, 0xf2, 0xba, 0xef, 0x0a, 0x91, 0x2e, 0xb4, 0x63, 0x14, 0x4b,
	0xce, 0x8a, 0xd2, 0x7e, 0xfa, 0xf0, 0xfb, 0xa1, 0xde, 0x14, 0x5e, 0xd1, 0xe8, 0xd7, 0xd1, 0x26,
	0xe5, 0x6b, 0x3f, 0x2d, 0x18, 0xc5, 0x5f, 0xd6, 0x28, 0x24, 0xf9, 0x02, 0xac, 0x68, 0x2d, 0x9f,
	0x73, 0xce, 0xe4, 0x46, 0xd7, 0xdc, 0x05, 0xca, 0x17, 0x62, 0x67, 0xcf, 0xfa, 0x85, 0xd8, 0x45,
	0x7a, 0xbf, 0x1f, 0x82, 0xfd, 0xaf, 0x92, 0x3f, 0x7c, 0x5c, 0xf2, 0x74, 0xf0, 0xb5, 0x6e, 0xed,
	0x63, 0xad, 0xeb, 0xd5, 0xc2, 0xff, 0xf3, 0xd7, 0x3f, 0x0c, 0xb0, 0xb6, 0x89, 0xff, 0x74, 0xec,
	0x29, 0x40, 0x70, 0x33, 0x0d, 0x83, 0xc7, 0xfb, 0xa1, 0x4f, 0x6d, 0xa3, 0x24, 0xa7, 0x73, 0x2f,
	0x98, 0xfa, 0x9e, 0x7d, 0x44, 0x5e, 0x42, 0xc7, 0x0b, 0xfc, 0x47, 0x7a, 0x1b, 0x84, 0x43, 0xff,
	0x9d, 0x17, 0xd8, 0xc7, 0xe4, 0x05, 0xb4, 0x87, 0xa3, 0xc7, 0x70, 0xe4, 0x07, 0x33, 0xea, 0xdd,
	0xd9, 0x8d, 0xb2, 0x40, 0x19, 0xb8, 0xf7, 0xfc, 0xbb, 0x07, 0x6a, 0x9b, 0xe4, 0x04, 0x5a, 0x25,
	0x9e, 0xfb, 0xd3, 0x99, 0xdd, 0x2c, 0xcb, 0x8d, 0xe6, 0xf7, 0xe1, 0xcc, 0xbb, 0xb6, 0x5b, 0xe4,
	0x0c, 0xec, 0x91, 0x47, 0xc7, 0xb7, 0xd7, 0xd7, 0xa1, 0x17, 0x8c, 0xc3, 0x77, 0xe5, 0x76, 0x58,
	0xa4, 0x03, 0xd6, 0xcd, 0xfb, 0xb9, 0x7f, 0x17, 0x8e, 0xc7, 0x9e, 0x0d, 0xc4, 0x82, 0xc6, 0xe4,
	0x61, 0xfe, 0x7e, 0x6a, 0xb7, 0x87, 0x17, 0xe0, 0x2c, 0xf3, 0xd4, 0xc5, 0x24, 0xe6, 0xec, 0x37,
	0x77, 0x99, 0x67, 0x4b, 0x86, 0x7c, 0x85, 0xe5, 0x68, 0x86, 0xe6, 0xa4, 0xb4, 0xbd, 0x98, 0x18,
	0x3f, 0x57, 0x8f, 0xfc, 0xc2, 0x54, 0x7b, 0x70, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d,
	0x04, 0x7e, 0xf4, 0x00, 0x06, 0x00, 0x00,
}
