// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.11.4
// source: empi.proto

package apiv1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CymruEmpiRequest_Authority int32

const (
	CymruEmpiRequest_UNKNOWN          CymruEmpiRequest_Authority = 0
	CymruEmpiRequest_NHS_NUMBER       CymruEmpiRequest_Authority = 1
	CymruEmpiRequest_SWANSEA          CymruEmpiRequest_Authority = 3
	CymruEmpiRequest_ANEURIN_BEVAN    CymruEmpiRequest_Authority = 4
	CymruEmpiRequest_BCU_CENTRAL      CymruEmpiRequest_Authority = 5
	CymruEmpiRequest_BCU_MAELOR       CymruEmpiRequest_Authority = 6
	CymruEmpiRequest_BCU_WEST         CymruEmpiRequest_Authority = 7
	CymruEmpiRequest_CWM_TAF          CymruEmpiRequest_Authority = 8
	CymruEmpiRequest_CARDIFF_AND_VALE CymruEmpiRequest_Authority = 9
	CymruEmpiRequest_HYWEL_DDA        CymruEmpiRequest_Authority = 10
	CymruEmpiRequest_POWYS            CymruEmpiRequest_Authority = 11
)

// Enum value maps for CymruEmpiRequest_Authority.
var (
	CymruEmpiRequest_Authority_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "NHS_NUMBER",
		3:  "SWANSEA",
		4:  "ANEURIN_BEVAN",
		5:  "BCU_CENTRAL",
		6:  "BCU_MAELOR",
		7:  "BCU_WEST",
		8:  "CWM_TAF",
		9:  "CARDIFF_AND_VALE",
		10: "HYWEL_DDA",
		11: "POWYS",
	}
	CymruEmpiRequest_Authority_value = map[string]int32{
		"UNKNOWN":          0,
		"NHS_NUMBER":       1,
		"SWANSEA":          3,
		"ANEURIN_BEVAN":    4,
		"BCU_CENTRAL":      5,
		"BCU_MAELOR":       6,
		"BCU_WEST":         7,
		"CWM_TAF":          8,
		"CARDIFF_AND_VALE": 9,
		"HYWEL_DDA":        10,
		"POWYS":            11,
	}
)

func (x CymruEmpiRequest_Authority) Enum() *CymruEmpiRequest_Authority {
	p := new(CymruEmpiRequest_Authority)
	*p = x
	return p
}

func (x CymruEmpiRequest_Authority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CymruEmpiRequest_Authority) Descriptor() protoreflect.EnumDescriptor {
	return file_empi_proto_enumTypes[0].Descriptor()
}

func (CymruEmpiRequest_Authority) Type() protoreflect.EnumType {
	return &file_empi_proto_enumTypes[0]
}

func (x CymruEmpiRequest_Authority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CymruEmpiRequest_Authority.Descriptor instead.
func (CymruEmpiRequest_Authority) EnumDescriptor() ([]byte, []int) {
	return file_empi_proto_rawDescGZIP(), []int{1, 0}
}

//
// Internal (module) proprietary requests
//
type RawCymruEmpiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authority  string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
}

func (x *RawCymruEmpiRequest) Reset() {
	*x = RawCymruEmpiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_empi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawCymruEmpiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCymruEmpiRequest) ProtoMessage() {}

func (x *RawCymruEmpiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_empi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCymruEmpiRequest.ProtoReflect.Descriptor instead.
func (*RawCymruEmpiRequest) Descriptor() ([]byte, []int) {
	return file_empi_proto_rawDescGZIP(), []int{0}
}

func (x *RawCymruEmpiRequest) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *RawCymruEmpiRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type CymruEmpiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authority  CymruEmpiRequest_Authority `protobuf:"varint,1,opt,name=authority,proto3,enum=apiv1.CymruEmpiRequest_Authority" json:"authority,omitempty"`
	Identifier string                     `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
}

func (x *CymruEmpiRequest) Reset() {
	*x = CymruEmpiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_empi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CymruEmpiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CymruEmpiRequest) ProtoMessage() {}

func (x *CymruEmpiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_empi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CymruEmpiRequest.ProtoReflect.Descriptor instead.
func (*CymruEmpiRequest) Descriptor() ([]byte, []int) {
	return file_empi_proto_rawDescGZIP(), []int{1}
}

func (x *CymruEmpiRequest) GetAuthority() CymruEmpiRequest_Authority {
	if x != nil {
		return x.Authority
	}
	return CymruEmpiRequest_UNKNOWN
}

func (x *CymruEmpiRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

var File_empi_proto protoreflect.FileDescriptor

var file_empi_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x6d, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x70,
	0x69, 0x76, 0x31, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53,
	0x0a, 0x13, 0x52, 0x61, 0x77, 0x43, 0x79, 0x6d, 0x72, 0x75, 0x45, 0x6d, 0x70, 0x69, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x22, 0xaa, 0x02, 0x0a, 0x10, 0x43, 0x79, 0x6d, 0x72, 0x75, 0x45, 0x6d, 0x70,
	0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x61, 0x70,
	0x69, 0x76, 0x31, 0x2e, 0x43, 0x79, 0x6d, 0x72, 0x75, 0x45, 0x6d, 0x70, 0x69, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x09,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0xb4, 0x01, 0x0a, 0x09, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x48, 0x53, 0x5f, 0x4e, 0x55, 0x4d, 0x42,
	0x45, 0x52, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x57, 0x41, 0x4e, 0x53, 0x45, 0x41, 0x10,
	0x03, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x4e, 0x45, 0x55, 0x52, 0x49, 0x4e, 0x5f, 0x42, 0x45, 0x56,
	0x41, 0x4e, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x43, 0x55, 0x5f, 0x43, 0x45, 0x4e, 0x54,
	0x52, 0x41, 0x4c, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x43, 0x55, 0x5f, 0x4d, 0x41, 0x45,
	0x4c, 0x4f, 0x52, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x43, 0x55, 0x5f, 0x57, 0x45, 0x53,
	0x54, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x57, 0x4d, 0x5f, 0x54, 0x41, 0x46, 0x10, 0x08,
	0x12, 0x14, 0x0a, 0x10, 0x43, 0x41, 0x52, 0x44, 0x49, 0x46, 0x46, 0x5f, 0x41, 0x4e, 0x44, 0x5f,
	0x56, 0x41, 0x4c, 0x45, 0x10, 0x09, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x59, 0x57, 0x45, 0x4c, 0x5f,
	0x44, 0x44, 0x41, 0x10, 0x0a, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4f, 0x57, 0x59, 0x53, 0x10, 0x0b,
	0x32, 0xdd, 0x01, 0x0a, 0x09, 0x57, 0x61, 0x6c, 0x65, 0x73, 0x45, 0x4d, 0x50, 0x49, 0x12, 0x70,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x61, 0x77, 0x45, 0x4d, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x77, 0x43,
	0x79, 0x6d, 0x72, 0x75, 0x45, 0x6d, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x61, 0x70, 0x69, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x22,
	0x2f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x29, 0x12, 0x27, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x61, 0x6c,
	0x65, 0x73, 0x2d, 0x65, 0x6d, 0x70, 0x69, 0x2f, 0x7b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x7d, 0x2f, 0x7b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x7d,
	0x12, 0x5e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x45, 0x4d, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x76, 0x31, 0x2e, 0x43, 0x79, 0x6d, 0x72, 0x75,
	0x45, 0x6d, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x61, 0x70,
	0x69, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x23, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x61, 0x6c, 0x65, 0x73, 0x2d, 0x65,
	0x6d, 0x70, 0x69, 0x2f, 0x7b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x7d,
	0x42, 0x3d, 0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x6c, 0x64, 0x72, 0x69, 0x78, 0x2e, 0x63,
	0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x5a, 0x21, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x72, 0x64, 0x6c, 0x65, 0x2f,
	0x63, 0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_empi_proto_rawDescOnce sync.Once
	file_empi_proto_rawDescData = file_empi_proto_rawDesc
)

func file_empi_proto_rawDescGZIP() []byte {
	file_empi_proto_rawDescOnce.Do(func() {
		file_empi_proto_rawDescData = protoimpl.X.CompressGZIP(file_empi_proto_rawDescData)
	})
	return file_empi_proto_rawDescData
}

var file_empi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_empi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_empi_proto_goTypes = []interface{}{
	(CymruEmpiRequest_Authority)(0), // 0: apiv1.CymruEmpiRequest.Authority
	(*RawCymruEmpiRequest)(nil),     // 1: apiv1.RawCymruEmpiRequest
	(*CymruEmpiRequest)(nil),        // 2: apiv1.CymruEmpiRequest
	(*Patient)(nil),                 // 3: apiv1.Patient
}
var file_empi_proto_depIdxs = []int32{
	0, // 0: apiv1.CymruEmpiRequest.authority:type_name -> apiv1.CymruEmpiRequest.Authority
	1, // 1: apiv1.WalesEMPI.GetRawEMPIRequest:input_type -> apiv1.RawCymruEmpiRequest
	2, // 2: apiv1.WalesEMPI.GetEMPIRequest:input_type -> apiv1.CymruEmpiRequest
	3, // 3: apiv1.WalesEMPI.GetRawEMPIRequest:output_type -> apiv1.Patient
	3, // 4: apiv1.WalesEMPI.GetEMPIRequest:output_type -> apiv1.Patient
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_empi_proto_init() }
func file_empi_proto_init() {
	if File_empi_proto != nil {
		return
	}
	file_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_empi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawCymruEmpiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_empi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CymruEmpiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_empi_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_empi_proto_goTypes,
		DependencyIndexes: file_empi_proto_depIdxs,
		EnumInfos:         file_empi_proto_enumTypes,
		MessageInfos:      file_empi_proto_msgTypes,
	}.Build()
	File_empi_proto = out.File
	file_empi_proto_rawDesc = nil
	file_empi_proto_goTypes = nil
	file_empi_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalesEMPIClient is the client API for WalesEMPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalesEMPIClient interface {
	GetRawEMPIRequest(ctx context.Context, in *RawCymruEmpiRequest, opts ...grpc.CallOption) (*Patient, error)
	GetEMPIRequest(ctx context.Context, in *CymruEmpiRequest, opts ...grpc.CallOption) (*Patient, error)
}

type walesEMPIClient struct {
	cc grpc.ClientConnInterface
}

func NewWalesEMPIClient(cc grpc.ClientConnInterface) WalesEMPIClient {
	return &walesEMPIClient{cc}
}

func (c *walesEMPIClient) GetRawEMPIRequest(ctx context.Context, in *RawCymruEmpiRequest, opts ...grpc.CallOption) (*Patient, error) {
	out := new(Patient)
	err := c.cc.Invoke(ctx, "/apiv1.WalesEMPI/GetRawEMPIRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walesEMPIClient) GetEMPIRequest(ctx context.Context, in *CymruEmpiRequest, opts ...grpc.CallOption) (*Patient, error) {
	out := new(Patient)
	err := c.cc.Invoke(ctx, "/apiv1.WalesEMPI/GetEMPIRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalesEMPIServer is the server API for WalesEMPI service.
type WalesEMPIServer interface {
	GetRawEMPIRequest(context.Context, *RawCymruEmpiRequest) (*Patient, error)
	GetEMPIRequest(context.Context, *CymruEmpiRequest) (*Patient, error)
}

// UnimplementedWalesEMPIServer can be embedded to have forward compatible implementations.
type UnimplementedWalesEMPIServer struct {
}

func (*UnimplementedWalesEMPIServer) GetRawEMPIRequest(context.Context, *RawCymruEmpiRequest) (*Patient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRawEMPIRequest not implemented")
}
func (*UnimplementedWalesEMPIServer) GetEMPIRequest(context.Context, *CymruEmpiRequest) (*Patient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEMPIRequest not implemented")
}

func RegisterWalesEMPIServer(s *grpc.Server, srv WalesEMPIServer) {
	s.RegisterService(&_WalesEMPI_serviceDesc, srv)
}

func _WalesEMPI_GetRawEMPIRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawCymruEmpiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalesEMPIServer).GetRawEMPIRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiv1.WalesEMPI/GetRawEMPIRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalesEMPIServer).GetRawEMPIRequest(ctx, req.(*RawCymruEmpiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalesEMPI_GetEMPIRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CymruEmpiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalesEMPIServer).GetEMPIRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiv1.WalesEMPI/GetEMPIRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalesEMPIServer).GetEMPIRequest(ctx, req.(*CymruEmpiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalesEMPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiv1.WalesEMPI",
	HandlerType: (*WalesEMPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRawEMPIRequest",
			Handler:    _WalesEMPI_GetRawEMPIRequest_Handler,
		},
		{
			MethodName: "GetEMPIRequest",
			Handler:    _WalesEMPI_GetEMPIRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "empi.proto",
}
