// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.11.4
// source: services.proto

package apiv1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PractitionerSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	System    string `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
}

func (x *PractitionerSearchRequest) Reset() {
	*x = PractitionerSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PractitionerSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PractitionerSearchRequest) ProtoMessage() {}

func (x *PractitionerSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PractitionerSearchRequest.ProtoReflect.Descriptor instead.
func (*PractitionerSearchRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

func (x *PractitionerSearchRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *PractitionerSearchRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PractitionerSearchRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *PractitionerSearchRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type IdentifierMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	System    string `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Value     string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TargetUri string `protobuf:"bytes,3,opt,name=target_uri,json=targetUri,proto3" json:"target_uri,omitempty"`
}

func (x *IdentifierMapRequest) Reset() {
	*x = IdentifierMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentifierMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifierMapRequest) ProtoMessage() {}

func (x *IdentifierMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifierMapRequest.ProtoReflect.Descriptor instead.
func (*IdentifierMapRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *IdentifierMapRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *IdentifierMapRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *IdentifierMapRequest) GetTargetUri() string {
	if x != nil {
		return x.TargetUri
	}
	return ""
}

var File_services_proto protoreflect.FileDescriptor

var file_services_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x61, 0x70, 0x69, 0x76, 0x31, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01,
	0x0a, 0x19, 0x50, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x14, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x72, 0x69,
	0x32, 0x87, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65,
	0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x6e, 0x0a, 0x12, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x50, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72,
	0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12,
	0x17, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65,
	0x72, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x30, 0x01, 0x32, 0xcc, 0x01, 0x0a, 0x0b, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x58, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x61, 0x70,
	0x69, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x1a, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x76,
	0x31, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f, 0x7b, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x7d, 0x12, 0x63, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x76, 0x31, 0x2e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x12, 0x1a, 0x2f,
	0x76, 0x31, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f, 0x7b, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x7d, 0x2f, 0x6d, 0x61, 0x70, 0x42, 0x3d, 0x0a, 0x18, 0x63, 0x6f, 0x6d,
	0x2e, 0x65, 0x6c, 0x64, 0x72, 0x69, 0x78, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x67,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x77, 0x61, 0x72, 0x64, 0x6c, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72,
	0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData = file_services_proto_rawDesc
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_proto_rawDescData)
	})
	return file_services_proto_rawDescData
}

var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_proto_goTypes = []interface{}{
	(*PractitionerSearchRequest)(nil), // 0: apiv1.PractitionerSearchRequest
	(*IdentifierMapRequest)(nil),      // 1: apiv1.IdentifierMapRequest
	(*Identifier)(nil),                // 2: apiv1.Identifier
	(*Practitioner)(nil),              // 3: apiv1.Practitioner
	(*any.Any)(nil),                   // 4: google.protobuf.Any
}
var file_services_proto_depIdxs = []int32{
	0, // 0: apiv1.PractitionerDirectory.SearchPractitioner:input_type -> apiv1.PractitionerSearchRequest
	2, // 1: apiv1.Identifiers.GetIdentifier:input_type -> apiv1.Identifier
	1, // 2: apiv1.Identifiers.MapIdentifier:input_type -> apiv1.IdentifierMapRequest
	3, // 3: apiv1.PractitionerDirectory.SearchPractitioner:output_type -> apiv1.Practitioner
	4, // 4: apiv1.Identifiers.GetIdentifier:output_type -> google.protobuf.Any
	2, // 5: apiv1.Identifiers.MapIdentifier:output_type -> apiv1.Identifier
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	file_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PractitionerSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentifierMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_rawDesc = nil
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PractitionerDirectoryClient is the client API for PractitionerDirectory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PractitionerDirectoryClient interface {
	SearchPractitioner(ctx context.Context, in *PractitionerSearchRequest, opts ...grpc.CallOption) (PractitionerDirectory_SearchPractitionerClient, error)
}

type practitionerDirectoryClient struct {
	cc grpc.ClientConnInterface
}

func NewPractitionerDirectoryClient(cc grpc.ClientConnInterface) PractitionerDirectoryClient {
	return &practitionerDirectoryClient{cc}
}

func (c *practitionerDirectoryClient) SearchPractitioner(ctx context.Context, in *PractitionerSearchRequest, opts ...grpc.CallOption) (PractitionerDirectory_SearchPractitionerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PractitionerDirectory_serviceDesc.Streams[0], "/apiv1.PractitionerDirectory/SearchPractitioner", opts...)
	if err != nil {
		return nil, err
	}
	x := &practitionerDirectorySearchPractitionerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PractitionerDirectory_SearchPractitionerClient interface {
	Recv() (*Practitioner, error)
	grpc.ClientStream
}

type practitionerDirectorySearchPractitionerClient struct {
	grpc.ClientStream
}

func (x *practitionerDirectorySearchPractitionerClient) Recv() (*Practitioner, error) {
	m := new(Practitioner)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PractitionerDirectoryServer is the server API for PractitionerDirectory service.
type PractitionerDirectoryServer interface {
	SearchPractitioner(*PractitionerSearchRequest, PractitionerDirectory_SearchPractitionerServer) error
}

// UnimplementedPractitionerDirectoryServer can be embedded to have forward compatible implementations.
type UnimplementedPractitionerDirectoryServer struct {
}

func (*UnimplementedPractitionerDirectoryServer) SearchPractitioner(*PractitionerSearchRequest, PractitionerDirectory_SearchPractitionerServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchPractitioner not implemented")
}

func RegisterPractitionerDirectoryServer(s *grpc.Server, srv PractitionerDirectoryServer) {
	s.RegisterService(&_PractitionerDirectory_serviceDesc, srv)
}

func _PractitionerDirectory_SearchPractitioner_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PractitionerSearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PractitionerDirectoryServer).SearchPractitioner(m, &practitionerDirectorySearchPractitionerServer{stream})
}

type PractitionerDirectory_SearchPractitionerServer interface {
	Send(*Practitioner) error
	grpc.ServerStream
}

type practitionerDirectorySearchPractitionerServer struct {
	grpc.ServerStream
}

func (x *practitionerDirectorySearchPractitionerServer) Send(m *Practitioner) error {
	return x.ServerStream.SendMsg(m)
}

var _PractitionerDirectory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiv1.PractitionerDirectory",
	HandlerType: (*PractitionerDirectoryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchPractitioner",
			Handler:       _PractitionerDirectory_SearchPractitioner_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services.proto",
}

// IdentifiersClient is the client API for Identifiers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentifiersClient interface {
	GetIdentifier(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*any.Any, error)
	MapIdentifier(ctx context.Context, in *IdentifierMapRequest, opts ...grpc.CallOption) (*Identifier, error)
}

type identifiersClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentifiersClient(cc grpc.ClientConnInterface) IdentifiersClient {
	return &identifiersClient{cc}
}

func (c *identifiersClient) GetIdentifier(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*any.Any, error) {
	out := new(any.Any)
	err := c.cc.Invoke(ctx, "/apiv1.Identifiers/GetIdentifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identifiersClient) MapIdentifier(ctx context.Context, in *IdentifierMapRequest, opts ...grpc.CallOption) (*Identifier, error) {
	out := new(Identifier)
	err := c.cc.Invoke(ctx, "/apiv1.Identifiers/MapIdentifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentifiersServer is the server API for Identifiers service.
type IdentifiersServer interface {
	GetIdentifier(context.Context, *Identifier) (*any.Any, error)
	MapIdentifier(context.Context, *IdentifierMapRequest) (*Identifier, error)
}

// UnimplementedIdentifiersServer can be embedded to have forward compatible implementations.
type UnimplementedIdentifiersServer struct {
}

func (*UnimplementedIdentifiersServer) GetIdentifier(context.Context, *Identifier) (*any.Any, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentifier not implemented")
}
func (*UnimplementedIdentifiersServer) MapIdentifier(context.Context, *IdentifierMapRequest) (*Identifier, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapIdentifier not implemented")
}

func RegisterIdentifiersServer(s *grpc.Server, srv IdentifiersServer) {
	s.RegisterService(&_Identifiers_serviceDesc, srv)
}

func _Identifiers_GetIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifiersServer).GetIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiv1.Identifiers/GetIdentifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifiersServer).GetIdentifier(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identifiers_MapIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifierMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifiersServer).MapIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiv1.Identifiers/MapIdentifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifiersServer).MapIdentifier(ctx, req.(*IdentifierMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Identifiers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiv1.Identifiers",
	HandlerType: (*IdentifiersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIdentifier",
			Handler:    _Identifiers_GetIdentifier_Handler,
		},
		{
			MethodName: "MapIdentifier",
			Handler:    _Identifiers_MapIdentifier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
